### ISSUE TITLE
Interested to demo your extension in a joined Areopa webinar?

### ISSUE THREAD

**Issue by lvanvugt** [edyspider/ALStructureCreator#1]
Hey Eder,

Are you interested in demoing your VSCode extension in a [Areopa](https://areopa.academy/) webinar?
The idea is to have AL VSCode extension domed to the community.

If you're interested please let me know. Mail to: webinars@areopa.academy.

b rg
Luc van Vugt

**Comment by edyspider** [comment]
Hi Luc,

Sorry for the delay response. I have not been worked with this project for some time.
I am about to about to update it and add new features, maybe after the update would be more insterested in demoing it.

best regards,
Eder Leal da Silva

**Comment by lvanvugt** [comment]
Great. Let me know when it's done.
