### ISSUE TITLE
Super project , I have suggestion for that

### ISSUE THREAD

**Issue by soroushabt** [edyspider/ALStructureCreator#15]
could you add another layer for defining other languages? I mean at the first, I can specify the program language after that give me the directory I already defined

**Comment by edyspider** [comment]
Hi, sorry for the delay. Last year I dived into a different kind of projects.
Meanwhile, I went ahead and developed a new vscode extension that meets your suggestion.
You can take a look at [VSCodeProjectFolderManagement](https://marketplace.visualstudio.com/items?itemName=EdySpider.vscodeprojectfoldermanagement)
