### ISSUE TITLE
New folder: Documents

### ISSUE THREAD

**Issue by FarreLindahl** [edyspider/ALStructureCreator#2]
Hi,

First thank you for your extension

Is it possible to create my own folders eg. Documents and if the answer is yes could you show how to=

Thanks in advance

Best regards

Preben

**Comment by FarreLindahl** [comment]
Hi Éder,

Many thanks for your quick response, looking forward to the new version

Best regards
Preben

Få Outlook til Android<https://aka.ms/ghei36>
________________________________

**Comment by edyspider** [comment]
Hi Preben,
Hope you are well.

The new version can now be customized to add new folders to the al structure, so it can be created automatically.
It is not documented yet but to add new folders, you must change the settings.json of the extension. You just have to add the following parameters: name, autocreate.
e.g:
```
"document":
  {
    "name": "docs",
    "autocreate": true
  }
```

**Comment by FarreLindahl** [comment]
Hi Det

Many thanks for your update

Best regards

Preben

Få Outlook til Android<https://aka.ms/ghei36>

________________________________
