### ISSUE TITLE
"requestpage" property

### ISSUE THREAD

**Issue by domingosbarreto** [edyspider/ALStructureCreator#5]
Hi,
Although it would be great to have a RequestPage object type in AL, as suggested in [this link](https://experience.dynamics.com/ideas/idea/?ideaid=eca1fdbb-960c-ec11-b76a-0003ff45c39c), I think that at the moment there is no need for the property "requestpage".

**Comment by edyspider** [comment]
Hi Domingos,
Thank you for the suggestion.
This issue is resolved in the new version of the extension.

If any changes was made in your settings file, you probably must first reset the settings and then copy again the json settings to your settings file.

Best regards

**Comment by edyspider** [comment]
Hi Domingos,
Thank you for the suggestion.
This issue is resolved in the new version of the extension.

If any changes was made in your settings file, you probably must first reset the settings and then copy again the json settings to your settings file.

Best regards
